name: job_post_model
channels:
  - defaults
dependencies:
  - python=3.10.9 
  - pip
  - pip:
      - Flask==2.1.1
      - gunicorn==20.1.0
      - joblib==1.1.1
      - nltk==3.6.6
      - numpy==1.22.3
      - pandas==1.4.1
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - matplotlib==3.4.3
      - vaderSentiment==3.3.2
      - spacy==3.2.1
      - py-readability-metrics==1.4.5
      - textstat==0.7.3
      - tqdm==4.62.3
